"""empty message

Revision ID: a438ddf5983b
Revises: 523b085bec8b
Create Date: 2022-07-29 13:14:13.312826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a438ddf5983b'
down_revision = '523b085bec8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fuel_prices', sa.Column('name', sa.String(), nullable=False))
    op.add_column('fuel_prices', sa.Column('type_alt', sa.Integer(), nullable=False))
    op.drop_column('fuel_prices', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fuel_prices', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('fuel_prices', 'type_alt')
    op.drop_column('fuel_prices', 'name')
    # ### end Alembic commands ###
