"""empty message

Revision ID: bc34ab19e455
Revises: a438ddf5983b
Create Date: 2022-07-31 16:51:55.911969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc34ab19e455'
down_revision = 'a438ddf5983b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fuel_prices', sa.Column('last_updated', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fuel_prices', 'last_updated')
    # ### end Alembic commands ###
